### ISSUE TITLE
"14. Make video clips w/ face alignment" is missing?

### ISSUE THREAD

**Issue by room3dev** [shaoanlu/faceswap-GAN#24]
I about to make mp4 output but I can't find "14. Make video clips w/ face alignment" in FaceSwap_GAN_v2_sz128_train.ipynb where I can find it?

**Comment by shaoanlu** [comment]
I did not integrate it into v2 model since the landmarks detection was not accurate on my data. Also there were some bugs when processing close-up frames. 

You can copy the piece of code from v1 jupyter notebook, and it should work in v2 model with slight modification. To be specific, modify the code between
```python
ae_input = cv2.resize(roi_image, (64,64))/255. * 2 - 1        
...
result = cv2.cvtColor(result, cv2.COLOR_BGR2RGB)
```
so that it is consistent with v2 video making part.

**Comment by room3dev** [comment]
I copy the code from v1 and edit input dimension to (128,128) and Its working now.
Thanks.  :+1:

**Comment by petergerten** [comment]
@room3dev could you post what exactly need to be changed? It seem to be more than just changing (64,64) to (128,128)
