### ISSUE TITLE
No preview screen showing while training

### ISSUE THREAD

**Issue by salre9501** [shaoanlu/faceswap-GAN#34]
Running FaceSwap_GAN_v2_train, but no preview screen is showing.

**Comment by shaoanlu** [comment]
Previews are shown in the jupyter notebook cell.

**Comment by salre9501** [comment]
Thanks. I converted it to py and ran it, so that's why. Also I trained it for about 7 hours but when I do the faceswap to video using FaceSwap_GAN_v2_test_video.ipynb, the results are very bad. The mask position isn't even on the face. Is this normal?

**Comment by shaoanlu** [comment]
It depends on your hardware and dataset.  I got good result after 15000 iterations.

**Comment by salre9501** [comment]
Ok I let it train for about 12 hours now and I'm just not seeing any difference in the converted video. FaceA is target face and FaceB folder has the images of the celeb. I see the outline of the mask but the face is exactly the same. I must've missed something.

**Comment by shaoanlu** [comment]
Does the preview results seems okay to you? If the previews are good, it can be something to do with the transform in video making: it try to transform faceA to faceA. 

The solution is to simply change `path_abgr_A` to `path_abgr_B` in `process_video()`. The name of the parameters might not be exactly the same because I dont have access to computer right now, but all you have to do is to change just one character: **A** to **B**.

**Comment by salre9501** [comment]
I couldn't find that line in FaceSwap_GAN_v2_test_video.ipynb, but I changed this line:

result, result_a = generate_face(ae_input, path_abgr_A, roi_size) to B

and it's working now. Should I also change this part?

whom2whom = "BtoA" # default trainsforming faceB to faceA

if whom2whom is "AtoB":
    path_func = path_abgr_B
elif whom2whom is "BtoA":
    path_func = path_abgr_A  #default path_abgr_A
else:
    print ("whom2whom should be either AtoB or BtoA")

**Comment by shaoanlu** [comment]
You don't have to if everything is working.
