### ISSUE TITLE
Why do you use 4 discriminators? 

### ISSUE THREAD

**Issue by albert10200** [shaoanlu/faceswap-GAN#82]
Why are you using 4 discriminators in the newest version of the code? Wouldn't 2 discriminators be enough to translate between face A -> B and face B -> A using XGAN?

**Comment by shaoanlu** [comment]
If you look into v2 model, the two discriminators take masked image as input. In such case, the loss gradient will not back-prop through those pixels where alpha_mask is zero (because the masked output is a multiplied result of the alpha mask). Thus in v2.1 model, I added additional discriminators that take images before masking as input to reinforce the gradient flow.
