### ISSUE TITLE
why sometimes  mtcnn_weight load take so much time(now always)

### ISSUE THREAD

**Issue by shadowwider** [shaoanlu/faceswap-GAN#87]
when I process video sometimes it token too much time,maybe 1min for 1 frame picture. I checked the most time cost is in  `pnet2.load(os.path.join("./mtcnn_weights/", 'det1.npy'), sess) ` and rnet2 ,onet2 load.
I don't know why,the weight file seems small. And when train model my PC not slow. 
Anyone have the same problem? And sometimes the video process become very quick,I don't know what make the different.

**Comment by shaoanlu** [comment]
This is due to the if statement in `process_video()` which reload mtcnn at the first 2 frames during video conversion. It solve a bug which has an unknown cause. You can try to remove the if statement and see if MTCNN still works. 

The bug is: MTCNN failed to detect any face once the program run the forward pass of GAN. I tried to look into it and found that the output of pnet was different once forward pass of GAN was called (given the same input image). 

Perhaps it has something to do with memory leakage, but I just couldn't locate the root cause. And somehow reloading MTCNN several times solves this issue (see how messy it is in MTCNN setup part), with a cost that it will take several minutes in the first 2~3 frames in video conversion.

**Comment by shadowwider** [comment]
thanks I got the point~
